//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace CreateSAPVoucherSV.CreateSAPVoucherSV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_UFIDA.U9.Cust.HXPPSV.CreateSAPVoucherSV.ICreateSV", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptionDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiLangDataDict))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFSoftUBFBusinessDataTransObjectBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplicationContext))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThreadContext))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlatformContext))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Exception[]))]
    public partial class CreateSVStub : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CreateSVStub() {
            this.Url = global::CreateSAPVoucherSV.Properties.Settings.Default.CreateSAPVoucherSV_CreateSAPVoucherSV_CreateSVStub;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoCompletedEventHandler DoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.UFIDA.org/UFIDA.U9.Cust.HXPPSV.CreateSAPVoucherSV.ICreateSV/Do", RequestNamespace="http://www.UFIDA.org", ResponseNamespace="http://www.UFIDA.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://www.UFIDA.org/EntityData")]
        public UFIDAU9CustHXPPSVCreateSAPVoucherSVCommonResultDTOData[] Do([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object context, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://www.UFIDA.org/EntityData")] UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherDTOData[] sAPU9GLVoucherDTOS, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="UFSoft.UBF.Exceptions")] out MessageBase[] outMessages) {
            object[] results = this.Invoke("Do", new object[] {
                        context,
                        sAPU9GLVoucherDTOS});
            outMessages = ((MessageBase[])(results[1]));
            return ((UFIDAU9CustHXPPSVCreateSAPVoucherSVCommonResultDTOData[])(results[0]));
        }
        
        /// <remarks/>
        public void DoAsync(object context, UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherDTOData[] sAPU9GLVoucherDTOS) {
            this.DoAsync(context, sAPU9GLVoucherDTOS, null);
        }
        
        /// <remarks/>
        public void DoAsync(object context, UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherDTOData[] sAPU9GLVoucherDTOS, object userState) {
            if ((this.DoOperationCompleted == null)) {
                this.DoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoOperationCompleted);
            }
            this.InvokeAsync("Do", new object[] {
                        context,
                        sAPU9GLVoucherDTOS}, this.DoOperationCompleted, userState);
        }
        
        private void OnDoOperationCompleted(object arg) {
            if ((this.DoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoCompleted(this, new DoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceExceptionDetail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    public partial class ExceptionDetail {
        
        private string helpLinkField;
        
        private ExceptionDetail innerExceptionField;
        
        private string messageField;
        
        private string stackTraceField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HelpLink {
            get {
                return this.helpLinkField;
            }
            set {
                this.helpLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExceptionDetail InnerException {
            get {
                return this.innerExceptionField;
            }
            set {
                this.innerExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    public partial class ServiceExceptionDetail : ExceptionDetail {
        
        private ExceptionBase exceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExceptionBase Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnknownException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityNotExistException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeInValidException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttrsContainerException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceLostException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ExceptionBase : Exception {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptionBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnknownException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityNotExistException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeInValidException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttrsContainerException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceLostException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class Exception {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class UnknownException : ExceptionBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityNotExistException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeInValidException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttrsContainerException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Business")]
    public partial class BusinessException : ExceptionBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Business")]
    public partial class EntityNotExistException : BusinessException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Business")]
    public partial class AttributeInValidException : BusinessException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Business")]
    public partial class AttrsContainerException : BusinessException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    public partial class ServiceException : ExceptionBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    public partial class ServiceLostException : ExceptionBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorDescriptor {
        
        private string categoryField;
        
        private string erroridField;
        
        private ErrorLevel levelField;
        
        private bool levelFieldSpecified;
        
        private string ownerField;
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorid {
            get {
                return this.erroridField;
            }
            set {
                this.erroridField = value;
            }
        }
        
        /// <remarks/>
        public ErrorLevel level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeStampSpecified {
            get {
                return this.timeStampFieldSpecified;
            }
            set {
                this.timeStampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public enum ErrorLevel {
        
        /// <remarks/>
        Debug,
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warn,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Fatal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorMessage {
        
        private ErrorDescriptor errDescriptorField;
        
        private string errorTypeField;
        
        private ErrorMessage[] innerMessagesField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ErrorDescriptor errDescriptor {
            get {
                return this.errDescriptorField;
            }
            set {
                this.errDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ErrorMessage[] innerMessages {
            get {
                return this.innerMessagesField;
            }
            set {
                this.innerMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="UFSoft.UBF.Util.Data")]
    public partial class MultiLangData {
        
        private string langTypeField;
        
        private string langValueField;
        
        private DataRowState stateField;
        
        private bool stateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LangType {
            get {
                return this.langTypeField;
            }
            set {
                this.langTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LangValue {
            get {
                return this.langValueField;
            }
            set {
                this.langValueField = value;
            }
        }
        
        /// <remarks/>
        public DataRowState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum DataRowState {
        
        /// <remarks/>
        Detached = 1,
        
        /// <remarks/>
        Unchanged = 2,
        
        /// <remarks/>
        Added = 4,
        
        /// <remarks/>
        Deleted = 8,
        
        /// <remarks/>
        Modified = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="UFSoft.UBF.Util.Data")]
    public partial class MultiLangDataDict {
        
        private MultiLangData[] _langsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MultiLangData[] _langs {
            get {
                return this._langsField;
            }
            set {
                this._langsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFIDAU9CustHXPPSVCreateSAPVoucherSVCommonResultDTOData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherLineDTOData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherDTOData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="UFSoft.UBF.Business.DataTransObjectBase", Namespace="http://www.UFIDA.org/EntityData")]
    public partial class UFSoftUBFBusinessDataTransObjectBase {
        
        private ObjectState sysStateField;
        
        private bool sysStateFieldSpecified;
        
        private string idField;
        
        private string refField;
        
        /// <remarks/>
        public ObjectState sysState {
            get {
                return this.sysStateField;
            }
            set {
                this.sysStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sysStateSpecified {
            get {
                return this.sysStateFieldSpecified;
            }
            set {
                this.sysStateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="IDREF")]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.PL.Engine")]
    public enum ObjectState {
        
        /// <remarks/>
        NotExist,
        
        /// <remarks/>
        Unchanged,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Inserted,
        
        /// <remarks/>
        Updated,
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Operating,
        
        /// <remarks/>
        NeedLoad,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="UFIDA.U9.Cust.HXPPSV.CreateSAPVoucherSV.CommonResultDTOData", Namespace="http://www.UFIDA.org/EntityData")]
    public partial class UFIDAU9CustHXPPSVCreateSAPVoucherSVCommonResultDTOData : UFSoftUBFBusinessDataTransObjectBase {
        
        private string m_companyCodeField;
        
        private bool m_isSuccessField;
        
        private bool m_isSuccessFieldSpecified;
        
        private string m_messageField;
        
        private long m_middleIdField;
        
        private bool m_middleIdFieldSpecified;
        
        private System.DateTime m_postDateField;
        
        private bool m_postDateFieldSpecified;
        
        private string m_sAPVoucherDisplayCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_companyCode {
            get {
                return this.m_companyCodeField;
            }
            set {
                this.m_companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool m_isSuccess {
            get {
                return this.m_isSuccessField;
            }
            set {
                this.m_isSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_isSuccessSpecified {
            get {
                return this.m_isSuccessFieldSpecified;
            }
            set {
                this.m_isSuccessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_message {
            get {
                return this.m_messageField;
            }
            set {
                this.m_messageField = value;
            }
        }
        
        /// <remarks/>
        public long m_middleId {
            get {
                return this.m_middleIdField;
            }
            set {
                this.m_middleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_middleIdSpecified {
            get {
                return this.m_middleIdFieldSpecified;
            }
            set {
                this.m_middleIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime m_postDate {
            get {
                return this.m_postDateField;
            }
            set {
                this.m_postDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_postDateSpecified {
            get {
                return this.m_postDateFieldSpecified;
            }
            set {
                this.m_postDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_sAPVoucherDisplayCode {
            get {
                return this.m_sAPVoucherDisplayCodeField;
            }
            set {
                this.m_sAPVoucherDisplayCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="UFIDA.U9.Cust.HXPPSV.CreateSAPVoucherSV.SAPU9GLVoucherLineDTOData", Namespace="http://www.UFIDA.org/EntityData")]
    public partial class UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherLineDTOData : UFSoftUBFBusinessDataTransObjectBase {
        
        private string m_abstractsField;
        
        private string m_accountCodeField;
        
        private string m_accountDescriptionField;
        
        private decimal m_accountedCrField;
        
        private bool m_accountedCrFieldSpecified;
        
        private decimal m_accountedDrField;
        
        private bool m_accountedDrFieldSpecified;
        
        private string m_assetsCodeField;
        
        private string m_assetsDescriptionField;
        
        private string m_bankAccountField;
        
        private string m_banksField;
        
        private string m_cashFlowCodeField;
        
        private string m_cashFlowDescriptionField;
        
        private string m_customerCodeField;
        
        private string m_customerDescriptionField;
        
        private string m_departmentCodeField;
        
        private string m_departmentNameField;
        
        private string m_employeeCodeField;
        
        private string m_employeeNameField;
        
        private decimal m_enteredCrField;
        
        private bool m_enteredCrFieldSpecified;
        
        private decimal m_enteredDrField;
        
        private bool m_enteredDrFieldSpecified;
        
        private string m_feeTypeEnumCodeField;
        
        private string m_feeTypeEnumDescriptionField;
        
        private string m_materialGroupCodeField;
        
        private string m_materialGroupDescriptionField;
        
        private string m_relCompCodeField;
        
        private string m_relCompNameField;
        
        private UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherDTOData m_sAPU9GLVoucherDTOField;
        
        private int m_serialNoField;
        
        private bool m_serialNoFieldSpecified;
        
        private string m_supplierCodeField;
        
        private string m_supplierDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_abstracts {
            get {
                return this.m_abstractsField;
            }
            set {
                this.m_abstractsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_accountCode {
            get {
                return this.m_accountCodeField;
            }
            set {
                this.m_accountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_accountDescription {
            get {
                return this.m_accountDescriptionField;
            }
            set {
                this.m_accountDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal m_accountedCr {
            get {
                return this.m_accountedCrField;
            }
            set {
                this.m_accountedCrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_accountedCrSpecified {
            get {
                return this.m_accountedCrFieldSpecified;
            }
            set {
                this.m_accountedCrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal m_accountedDr {
            get {
                return this.m_accountedDrField;
            }
            set {
                this.m_accountedDrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_accountedDrSpecified {
            get {
                return this.m_accountedDrFieldSpecified;
            }
            set {
                this.m_accountedDrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_assetsCode {
            get {
                return this.m_assetsCodeField;
            }
            set {
                this.m_assetsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_assetsDescription {
            get {
                return this.m_assetsDescriptionField;
            }
            set {
                this.m_assetsDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_bankAccount {
            get {
                return this.m_bankAccountField;
            }
            set {
                this.m_bankAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_banks {
            get {
                return this.m_banksField;
            }
            set {
                this.m_banksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_cashFlowCode {
            get {
                return this.m_cashFlowCodeField;
            }
            set {
                this.m_cashFlowCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_cashFlowDescription {
            get {
                return this.m_cashFlowDescriptionField;
            }
            set {
                this.m_cashFlowDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_customerCode {
            get {
                return this.m_customerCodeField;
            }
            set {
                this.m_customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_customerDescription {
            get {
                return this.m_customerDescriptionField;
            }
            set {
                this.m_customerDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_departmentCode {
            get {
                return this.m_departmentCodeField;
            }
            set {
                this.m_departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_departmentName {
            get {
                return this.m_departmentNameField;
            }
            set {
                this.m_departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_employeeCode {
            get {
                return this.m_employeeCodeField;
            }
            set {
                this.m_employeeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_employeeName {
            get {
                return this.m_employeeNameField;
            }
            set {
                this.m_employeeNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal m_enteredCr {
            get {
                return this.m_enteredCrField;
            }
            set {
                this.m_enteredCrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_enteredCrSpecified {
            get {
                return this.m_enteredCrFieldSpecified;
            }
            set {
                this.m_enteredCrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal m_enteredDr {
            get {
                return this.m_enteredDrField;
            }
            set {
                this.m_enteredDrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_enteredDrSpecified {
            get {
                return this.m_enteredDrFieldSpecified;
            }
            set {
                this.m_enteredDrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_feeTypeEnumCode {
            get {
                return this.m_feeTypeEnumCodeField;
            }
            set {
                this.m_feeTypeEnumCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_feeTypeEnumDescription {
            get {
                return this.m_feeTypeEnumDescriptionField;
            }
            set {
                this.m_feeTypeEnumDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_materialGroupCode {
            get {
                return this.m_materialGroupCodeField;
            }
            set {
                this.m_materialGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_materialGroupDescription {
            get {
                return this.m_materialGroupDescriptionField;
            }
            set {
                this.m_materialGroupDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_relCompCode {
            get {
                return this.m_relCompCodeField;
            }
            set {
                this.m_relCompCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_relCompName {
            get {
                return this.m_relCompNameField;
            }
            set {
                this.m_relCompNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherDTOData m_sAPU9GLVoucherDTO {
            get {
                return this.m_sAPU9GLVoucherDTOField;
            }
            set {
                this.m_sAPU9GLVoucherDTOField = value;
            }
        }
        
        /// <remarks/>
        public int m_serialNo {
            get {
                return this.m_serialNoField;
            }
            set {
                this.m_serialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_serialNoSpecified {
            get {
                return this.m_serialNoFieldSpecified;
            }
            set {
                this.m_serialNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_supplierCode {
            get {
                return this.m_supplierCodeField;
            }
            set {
                this.m_supplierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_supplierDescription {
            get {
                return this.m_supplierDescriptionField;
            }
            set {
                this.m_supplierDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="UFIDA.U9.Cust.HXPPSV.CreateSAPVoucherSV.SAPU9GLVoucherDTOData", Namespace="http://www.UFIDA.org/EntityData")]
    public partial class UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherDTOData : UFSoftUBFBusinessDataTransObjectBase {
        
        private string m_companyCodeField;
        
        private string m_companyNameField;
        
        private string m_currencyCodeField;
        
        private string m_currencyDescriptionField;
        
        private System.DateTime m_postDateField;
        
        private bool m_postDateFieldSpecified;
        
        private int m_postedPeriodField;
        
        private bool m_postedPeriodFieldSpecified;
        
        private UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherLineDTOData[] m_sAPU9GLVoucherLineDTOSField;
        
        private string m_sAPVoucherDisplayCodeField;
        
        private string m_sapAuditorField;
        
        private string m_sapCashierField;
        
        private string m_sapCreaterField;
        
        private string m_sapPosterField;
        
        private string m_voucherCategoryCodeField;
        
        private string m_voucherCategoryDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_companyCode {
            get {
                return this.m_companyCodeField;
            }
            set {
                this.m_companyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_companyName {
            get {
                return this.m_companyNameField;
            }
            set {
                this.m_companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_currencyCode {
            get {
                return this.m_currencyCodeField;
            }
            set {
                this.m_currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_currencyDescription {
            get {
                return this.m_currencyDescriptionField;
            }
            set {
                this.m_currencyDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime m_postDate {
            get {
                return this.m_postDateField;
            }
            set {
                this.m_postDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_postDateSpecified {
            get {
                return this.m_postDateFieldSpecified;
            }
            set {
                this.m_postDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int m_postedPeriod {
            get {
                return this.m_postedPeriodField;
            }
            set {
                this.m_postedPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool m_postedPeriodSpecified {
            get {
                return this.m_postedPeriodFieldSpecified;
            }
            set {
                this.m_postedPeriodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public UFIDAU9CustHXPPSVCreateSAPVoucherSVSAPU9GLVoucherLineDTOData[] m_sAPU9GLVoucherLineDTOS {
            get {
                return this.m_sAPU9GLVoucherLineDTOSField;
            }
            set {
                this.m_sAPU9GLVoucherLineDTOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_sAPVoucherDisplayCode {
            get {
                return this.m_sAPVoucherDisplayCodeField;
            }
            set {
                this.m_sAPVoucherDisplayCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_sapAuditor {
            get {
                return this.m_sapAuditorField;
            }
            set {
                this.m_sapAuditorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_sapCashier {
            get {
                return this.m_sapCashierField;
            }
            set {
                this.m_sapCashierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_sapCreater {
            get {
                return this.m_sapCreaterField;
            }
            set {
                this.m_sapCreaterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_sapPoster {
            get {
                return this.m_sapPosterField;
            }
            set {
                this.m_sapPosterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_voucherCategoryCode {
            get {
                return this.m_voucherCategoryCodeField;
            }
            set {
                this.m_voucherCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string m_voucherCategoryDescription {
            get {
                return this.m_voucherCategoryDescriptionField;
            }
            set {
                this.m_voucherCategoryDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="UFSoft.UBF.Exceptions")]
    public partial class MessageBase {
        
        private string attributeMetadataIDField;
        
        private string attributeNameField;
        
        private string entityFullNameField;
        
        private long entityIDField;
        
        private bool entityIDFieldSpecified;
        
        private string entityMetadataIDField;
        
        private short errorLevelField;
        
        private bool errorLevelFieldSpecified;
        
        private MessageBaseFormatState formatedField;
        
        private bool formatedFieldSpecified;
        
        private MessageBase[] innerMessagesField;
        
        private bool isValidEntityIDField;
        
        private bool isValidEntityIDFieldSpecified;
        
        private string localMessageField;
        
        private string orginalEntityFullNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string attributeMetadataID {
            get {
                return this.attributeMetadataIDField;
            }
            set {
                this.attributeMetadataIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entityFullName {
            get {
                return this.entityFullNameField;
            }
            set {
                this.entityFullNameField = value;
            }
        }
        
        /// <remarks/>
        public long entityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityIDSpecified {
            get {
                return this.entityIDFieldSpecified;
            }
            set {
                this.entityIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entityMetadataID {
            get {
                return this.entityMetadataIDField;
            }
            set {
                this.entityMetadataIDField = value;
            }
        }
        
        /// <remarks/>
        public short errorLevel {
            get {
                return this.errorLevelField;
            }
            set {
                this.errorLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorLevelSpecified {
            get {
                return this.errorLevelFieldSpecified;
            }
            set {
                this.errorLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MessageBaseFormatState formated {
            get {
                return this.formatedField;
            }
            set {
                this.formatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatedSpecified {
            get {
                return this.formatedFieldSpecified;
            }
            set {
                this.formatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MessageBase[] innerMessages {
            get {
                return this.innerMessagesField;
            }
            set {
                this.innerMessagesField = value;
            }
        }
        
        /// <remarks/>
        public bool isValidEntityID {
            get {
                return this.isValidEntityIDField;
            }
            set {
                this.isValidEntityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isValidEntityIDSpecified {
            get {
                return this.isValidEntityIDFieldSpecified;
            }
            set {
                this.isValidEntityIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string localMessage {
            get {
                return this.localMessageField;
            }
            set {
                this.localMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orginalEntityFullName {
            get {
                return this.orginalEntityFullNameField;
            }
            set {
                this.orginalEntityFullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MessageBase.FormatState", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Exceptions")]
    public enum MessageBaseFormatState {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Formatting,
        
        /// <remarks/>
        Formatted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ApplicationContext {
        
        private ArrayOfKeyValueOfanyTypeanyTypeKeyValueOfanyTypeanyType[] nameValueHasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfanyTypeanyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfanyTypeanyTypeKeyValueOfanyTypeanyType[] nameValueHas {
            get {
                return this.nameValueHasField;
            }
            set {
                this.nameValueHasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfanyTypeanyTypeKeyValueOfanyTypeanyType {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ThreadContext {
        
        private ArrayOfKeyValueOfanyTypeanyTypeKeyValueOfanyTypeanyType[] nameValueHasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfanyTypeanyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfanyTypeanyTypeKeyValueOfanyTypeanyType[] nameValueHas {
            get {
                return this.nameValueHasField;
            }
            set {
                this.nameValueHasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class PlatformContext {
        
        private object ctxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ctx {
            get {
                return this.ctxField;
            }
            set {
                this.ctxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DoCompletedEventHandler(object sender, DoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UFIDAU9CustHXPPSVCreateSAPVoucherSVCommonResultDTOData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UFIDAU9CustHXPPSVCreateSAPVoucherSVCommonResultDTOData[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public MessageBase[] outMessages {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageBase[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591